"""add models

Revision ID: 2d0151f4a11d
Revises: e8bca4a16f8e
Create Date: 2025-11-04 14:24:53.663847

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2d0151f4a11d'
down_revision = 'e8bca4a16f8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('docs1', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filename', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('file_path', sa.String(length=500), nullable=False))
        batch_op.add_column(sa.Column('upload_date', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('upload_by_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'users', ['upload_by_id'], ['id'])
        batch_op.drop_column('original_filename')
        batch_op.drop_column('stored_filename')
        batch_op.drop_column('upload_time')

    with op.batch_alter_table('docs2', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filename', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('file_path', sa.String(length=500), nullable=False))
        batch_op.add_column(sa.Column('upload_date', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('upload_by_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'users', ['upload_by_id'], ['id'])
        batch_op.drop_column('original_filename')
        batch_op.drop_column('stored_filename')
        batch_op.drop_column('upload_time')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('docs2', schema=None) as batch_op:
        batch_op.add_column(sa.Column('upload_time', mysql.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('stored_filename', mysql.VARCHAR(length=255), nullable=False))
        batch_op.add_column(sa.Column('original_filename', mysql.VARCHAR(length=255), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('upload_by_id')
        batch_op.drop_column('upload_date')
        batch_op.drop_column('file_path')
        batch_op.drop_column('filename')

    with op.batch_alter_table('docs1', schema=None) as batch_op:
        batch_op.add_column(sa.Column('upload_time', mysql.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('stored_filename', mysql.VARCHAR(length=255), nullable=False))
        batch_op.add_column(sa.Column('original_filename', mysql.VARCHAR(length=255), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('upload_by_id')
        batch_op.drop_column('upload_date')
        batch_op.drop_column('file_path')
        batch_op.drop_column('filename')

    # ### end Alembic commands ###
