"""Add chat models

Revision ID: 2ed52379b2f9
Revises: f3d439f55781
Create Date: 2025-11-11 18:26:56.294383

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2ed52379b2f9'
down_revision = 'f3d439f55781'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('message', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=True))
        batch_op.drop_index('ix_messages_between')
        batch_op.drop_index('ix_messages_created_at')
        batch_op.drop_index('ix_messages_receiver_id')
        batch_op.drop_index('ix_messages_sender_id')
        batch_op.drop_column('read_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('body')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('body', mysql.TEXT(), nullable=False))
        batch_op.add_column(sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True))
        batch_op.add_column(sa.Column('read_at', mysql.DATETIME(), nullable=True))
        batch_op.create_index('ix_messages_sender_id', ['sender_id'], unique=False)
        batch_op.create_index('ix_messages_receiver_id', ['receiver_id'], unique=False)
        batch_op.create_index('ix_messages_created_at', ['created_at'], unique=False)
        batch_op.create_index('ix_messages_between', ['sender_id', 'receiver_id', 'created_at'], unique=False)
        batch_op.drop_column('timestamp')
        batch_op.drop_column('message')

    # ### end Alembic commands ###
