"""add field case progress

Revision ID: 524cbd389626
Revises: a386cf7343dd
Create Date: 2025-11-03 15:56:19.383106

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '524cbd389626'
down_revision = 'a386cf7343dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('case_progress', sa.Integer(), nullable=True))
        batch_op.drop_column('case_progess')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('case_progess', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('case_progress')

    # ### end Alembic commands ###
