"""Add close_by field to Ticket

Revision ID: 6dbe2ca14c4e
Revises: 9ecd797ab468
Create Date: 2025-11-07 14:26:26.679662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6dbe2ca14c4e'
down_revision = '9ecd797ab468'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('close_by', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['close_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('close_by')

    # ### end Alembic commands ###
