"""Add close_by field to Ticket

Revision ID: 7c6152719668
Revises: 6dbe2ca14c4e
Create Date: 2025-11-07 14:44:12.178715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c6152719668'
down_revision = '6dbe2ca14c4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('move_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('move_by', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['move_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('move_by')
        batch_op.drop_column('move_date')

    # ### end Alembic commands ###
