"""Add close_by field to Ticket

Revision ID: 8889751c1062
Revises: 7c6152719668
Create Date: 2025-11-11 09:46:30.220980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8889751c1062'
down_revision = '7c6152719668'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_nominal_akhir', sa.Numeric(precision=15, scale=2), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenors', schema=None) as batch_op:
        batch_op.drop_column('total_nominal_akhir')

    # ### end Alembic commands ###
