"""add models

Revision ID: 9ecd797ab468
Revises: db6574aeeb63
Create Date: 2025-11-07 10:48:01.159713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ecd797ab468'
down_revision = 'db6574aeeb63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_nominal', sa.Numeric(precision=15, scale=2), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenors', schema=None) as batch_op:
        batch_op.drop_column('total_nominal')

    # ### end Alembic commands ###
