"""add field case progress

Revision ID: a386cf7343dd
Revises: d927a1dfa03e
Create Date: 2025-11-03 15:43:37.380417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a386cf7343dd'
down_revision = 'd927a1dfa03e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('case_progess', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.drop_column('case_progess')

    # ### end Alembic commands ###
