"""add models

Revision ID: db6574aeeb63
Revises: 2d0151f4a11d
Create Date: 2025-11-06 10:46:06.360696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db6574aeeb63'
down_revision = '2d0151f4a11d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nomor_kontrak', sa.String(length=500), nullable=False),
    sa.Column('tenor_1', sa.Integer(), nullable=True),
    sa.Column('nominal_tenor_1', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('ovd_1', sa.Date(), nullable=True),
    sa.Column('tenor_2', sa.Integer(), nullable=True),
    sa.Column('nominal_tenor_2', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('ovd_2', sa.Date(), nullable=True),
    sa.Column('tenor_3', sa.Integer(), nullable=True),
    sa.Column('nominal_tenor_3', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('ovd_3', sa.Date(), nullable=True),
    sa.Column('tenor_4', sa.Integer(), nullable=True),
    sa.Column('nominal_tenor_4', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('ovd_4', sa.Date(), nullable=True),
    sa.Column('tenor_5', sa.Integer(), nullable=True),
    sa.Column('nominal_tenor_5', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('ovd_5', sa.Date(), nullable=True),
    sa.Column('tenor_6', sa.Integer(), nullable=True),
    sa.Column('nominal_tenor_6', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('ovd_6', sa.Date(), nullable=True),
    sa.Column('tenor_7', sa.Integer(), nullable=True),
    sa.Column('nominal_tenor_7', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('ovd_7', sa.Date(), nullable=True),
    sa.Column('tenor_8', sa.Integer(), nullable=True),
    sa.Column('nominal_tenor_8', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('ovd_8', sa.Date(), nullable=True),
    sa.Column('tenor_9', sa.Integer(), nullable=True),
    sa.Column('nominal_tenor_9', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('ovd_9', sa.Date(), nullable=True),
    sa.Column('tenor_10', sa.Integer(), nullable=True),
    sa.Column('nominal_tenor_10', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('ovd_10', sa.Date(), nullable=True),
    sa.Column('tenor_11', sa.Integer(), nullable=True),
    sa.Column('nominal_tenor_11', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('ovd_11', sa.Date(), nullable=True),
    sa.Column('tenor_12', sa.Integer(), nullable=True),
    sa.Column('nominal_tenor_12', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('ovd_12', sa.Date(), nullable=True),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tenors')
    # ### end Alembic commands ###
